version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: financas-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: financas_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: financas_user
      MYSQL_PASSWORD: financas_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: