spring:
  application:
    name: financas-api

  datasource:
    url: jdbc:mysql://localhost:3306/financas_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
    secret: ${JWT_SECRET:minha-chave-secreta-temporaria-trocar-depois}
    expiration: 86400000